---
- hosts: localhost
  gather_facts: yes
  tasks:
  - import_role:
      name: homebrew
    when: ansible_os_family == "Darwin"

  - import_role:
      name: virtualbox

  - import_role:
      name: vagrant